services:
  postgres-beautique:
    image: postgres
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
    volumes:
      - 'd:\db-beautique:/var/lib/postgresql'
      - '.init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql'
    ports:
      - '3334:5432'
    networks:
      - beautique-network
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - beautique-network
    volumes:
      - 'd:\rabbitmq-data:/var/lib/rabbitmq'
      - 'd:\rabbitmq-log:/var/log/rabbitmq'

networks:
  beautique-network:
    driver: bridge

